use_frameworks!

platform :ios, '9.0'

target 'CNjacobBleManagerKit_Example' do
  pod 'CNjacobBleManagerKit', :path => '../'

  target 'CNjacobBleManagerKit_Tests' do
    inherit! :search_paths

    pod 'Kiwi'
  end
end
